export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER = "SET_USER";
export const SET_BOOKS = "SET_BOOKS";

export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_BOOKS_LOADING = "GET_BOOKS_LOADING";

export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_BOOKS_ERROR = "GET_BOOKS_ERROR";
